-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 21:02:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcursos` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `modidade` VARCHAR(10) NULL,
  `carga_horaria` INT(4) NULL COMMENT 'oi',
  `alunos_idalunos` INT NOT NULL,
  PRIMARY KEY (`idcursos`, `alunos_idalunos`),
  INDEX `fk_cursos_alunos1_idx` (`alunos_idalunos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_alunos1`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `mydb`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'v';


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `idturmas` INT NOT NULL,
  `numero _da_ turma` VARCHAR(20) NULL,
  `qtde_alunos` INT(100) NULL,
  `data_inicio` DATE NULL,
  `alunos_idalunos` INT NOT NULL,
  `cursos_idcursos` INT NOT NULL,
  `cursos_alunos_idalunos` INT NOT NULL,
  PRIMARY KEY (`idturmas`, `alunos_idalunos`, `cursos_idcursos`, `cursos_alunos_idalunos`),
  INDEX `fk_turmas_alunos1_idx` (`alunos_idalunos` ASC) VISIBLE,
  INDEX `fk_turmas_cursos1_idx` (`cursos_idcursos` ASC, `cursos_alunos_idalunos` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_alunos1`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `mydb`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_cursos1`
    FOREIGN KEY (`cursos_idcursos` , `cursos_alunos_idalunos`)
    REFERENCES `mydb`.`cursos` (`idcursos` , `alunos_idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `idMatricula` INT NOT NULL,
  `numero_matricula` INT(10) NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  `turmas_alunos_idalunos` INT NOT NULL,
  `data_matricula` DATE NULL,
  PRIMARY KEY (`idMatricula`, `turmas_idturmas`, `turmas_alunos_idalunos`),
  INDEX `fk_Matricula_turmas1_idx` (`turmas_idturmas` ASC, `turmas_alunos_idalunos` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_turmas1`
    FOREIGN KEY (`turmas_idturmas` , `turmas_alunos_idalunos`)
    REFERENCES `mydb`.`turmas` (`idturmas` , `alunos_idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `idalunos` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `data de nascimento` DATE NULL,
  `cpf` INT(11) NOT NULL,
  `genero` VARCHAR(10) NULL,
  `telefone` VARCHAR(14) GENERATED ALWAYS AS () VIRTUAL,
  `Matricula_idMatricula` INT NOT NULL,
  PRIMARY KEY (`idalunos`, `Matricula_idMatricula`),
  INDEX `fk_alunos_Matricula1_idx` (`Matricula_idMatricula` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_Matricula1`
    FOREIGN KEY (`Matricula_idMatricula`)
    REFERENCES `mydb`.`Matricula` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores` (
  `idProfessores` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `telefone` VARCHAR(12) NULL,
  `data_nascimento` DATE NULL,
  `genero` VARCHAR(10) NULL,
  PRIMARY KEY (`idProfessores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores_has_cursos` (
  `Professores_idProfessores` INT NOT NULL,
  `cursos_idcursos` INT NOT NULL,
  `cursos_alunos_idalunos` INT NOT NULL,
  PRIMARY KEY (`Professores_idProfessores`, `cursos_idcursos`, `cursos_alunos_idalunos`),
  INDEX `fk_Professores_has_cursos_cursos1_idx` (`cursos_idcursos` ASC, `cursos_alunos_idalunos` ASC) VISIBLE,
  INDEX `fk_Professores_has_cursos_Professores1_idx` (`Professores_idProfessores` ASC) VISIBLE,
  CONSTRAINT `fk_Professores_has_cursos_Professores1`
    FOREIGN KEY (`Professores_idProfessores`)
    REFERENCES `mydb`.`Professores` (`idProfessores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professores_has_cursos_cursos1`
    FOREIGN KEY (`cursos_idcursos` , `cursos_alunos_idalunos`)
    REFERENCES `mydb`.`cursos` (`idcursos` , `alunos_idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores_has_turmas` (
  `Professores_idProfessores` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  `turmas_alunos_idalunos` INT NOT NULL,
  `turmas_cursos_idcursos` INT NOT NULL,
  `turmas_cursos_alunos_idalunos` INT NOT NULL,
  PRIMARY KEY (`Professores_idProfessores`, `turmas_idturmas`, `turmas_alunos_idalunos`, `turmas_cursos_idcursos`, `turmas_cursos_alunos_idalunos`),
  INDEX `fk_Professores_has_turmas_turmas1_idx` (`turmas_idturmas` ASC, `turmas_alunos_idalunos` ASC, `turmas_cursos_idcursos` ASC, `turmas_cursos_alunos_idalunos` ASC) VISIBLE,
  INDEX `fk_Professores_has_turmas_Professores1_idx` (`Professores_idProfessores` ASC) VISIBLE,
  CONSTRAINT `fk_Professores_has_turmas_Professores1`
    FOREIGN KEY (`Professores_idProfessores`)
    REFERENCES `mydb`.`Professores` (`idProfessores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professores_has_turmas_turmas1`
    FOREIGN KEY (`turmas_idturmas` , `turmas_alunos_idalunos` , `turmas_cursos_idcursos` , `turmas_cursos_alunos_idalunos`)
    REFERENCES `mydb`.`turmas` (`idturmas` , `alunos_idalunos` , `cursos_idcursos` , `cursos_alunos_idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
